fluent-bit - use ghcr.io instead of cr.fluentbit.io
podman pull cr.fluentbit.io/fluent/fluent-bit:latest
Error: copying system image from manifest list: reading blob sha256:bfb59b82a9b65e47d485e53b3e815bca3b3e21a095bd0cb88ced9ac0b48062bf: fetching blob: StatusCode: 403, <?xml version="1.0" encoding="UTF-8"?>
<Error><Cod...

Change-Id: I4c21989f621e4716a2d0a5acf6cc082afa20f6bf